# Site settings
title: Log Horizon(記録の地平線)
email: rho[DOT]ajax[AT]Gmail 
description: > # this means to ignore newlines until "baseurl:"
  Cogito ergo sum.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Shiroyasha_Gin
github_username:  Rhoajax

# Build settings
markdown: kramdown
